name: Login e2e tests

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]
jobs:
  playwright:
    name: "Login e2e tests"
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.46.1-jammy
    steps:
      - uses: actions/checkout@v4
      - name: enable corepack
        run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "yarn"
      - name: Install dependencies
        run: yarn install
      - name: Enter login client
        run: cd packages/login
      - name: Build test version
        run: yarn test:build
      - name: Run tests
        run: yarn test:e2e
      - name: Get path
        run: pwd
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
