name: Frontend actions

on:
  push:
    branches: [master]
    paths: [packages/login/**, packages/shared/**]
  pull_request:
    branches: [master]
    paths: [packages/login/**, packages/shared/**]
jobs:
  eslint:
    name: "Login and doceditor lint"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: enable corepack
        run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "yarn"
      - name: Install dependencies
        run: yarn install
      - name: Link login and doceditor
        run: yarn lint
