name: Playwright Tests

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]
jobs:
  playwright:
    name: "Playwright Tests"
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.46.1-jammy
    steps:
      - uses: actions/checkout@v4
      - name: enable corepack
        run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "yarn"
      - name: Install dependencies
        run: yarn install
      - name: Build test version
        run: yarn test:build
      - name: Run tests
        run: yarn test:e2e
